# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: HaiNguyen.MechvibesDx
PackageVersion: 0.3.0
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: MechvibesDx
ReleaseDate: 2025-06-19
AppsAndFeaturesEntries:
- ProductCode: MechvibesDx
InstallationMetadata:
  DefaultInstallLocation: placeholder\MechvibesDx
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hainguyents13/mechvibes-dx/releases/download/v0.3.0/MechvibesDx_0.3.0_x64-setup.exe
  InstallerSha256: B233D7BAA7C98F318836EBBA49CE647530711F2130337F0AEDE13A3AAC3FDDD7
ManifestType: installer
ManifestVersion: 1.10.0

